#!/bin/bash

test_mkdkr_run_simple() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  run: echo "hello world!"
  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_return_error() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  (run: noooooo)&

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_arguments() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: ubuntu

  run: apt-get update -qq
  run: apt-get install htop -y
  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_line-break() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  run: apk add \
    curl \
    htop \
    bash

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_escape() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: debian

  run: apt-get update \&\& \
    apt-get install \
      curl \
      htop -y

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_pipe() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  run: ls -la \| wc -l

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_redirect_internal() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  run: ls -la \> /tmp/my-file

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_get_output() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  OUT=$(run: ls -la)

  echo $OUT

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_var_run() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine

  var-run: "test1" echo 'test'
  run: echo "$$test1"
  var-run: 'iam' whoami
  run: echo '$$iam'
  var-run: w hostname
  run: echo $$w

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

test_mkdkr_print_env_var() {
  # shellcheck disable=SC1091
  source .mkdkr
  unset MKDKR_JOB_NAME

  NAME="simple_instance"
  _job_uniq_name "${NAME}"

  instance: alpine \
    --env "name=foo" \
    --env "last=bar" \
    --env "fullname=foo bar"

  run: echo '$name'
  run: echo '$last'
  run: echo '$fullname'

  _job_destroy

  _pretty "light_green" "\nRan 1 assert(s)\n"
}

# shellcheck disable=SC1091
. ./shunit2