#!/bin/bash

test_job_name() {
    # shellcheck disable=SC1091
    source .mkdkr

    JOBS=("simple" "with/slash" "with\\backslash" "with_undercode" "012" "+=" "!@#$%^&*()_+{}'")

    for NAME in "${JOBS[@]}"; do
        .... "$NAME" > /dev/null

        assertNotNull "$JOB_NAME"
        [[ "$?" == "0" ]] && \
            _prn_exec "assert ${JOB_NAME} is not null [ OK ]"

        assertContains "$JOB_NAME" "$(echo "$NAME" | sed 's/\//_/g')"
        [[ "$?" == "0" ]] && \
            _prn_exec "assert ${JOB_NAME} contains current name [ OK ]"

        assertEquals "$([[ "$JOB_NAME" =~ ^.*_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12} ]] && echo true )" "true"
        [[ "$?" == "0" ]] && \
            _prn_exec "assert ${JOB_NAME} contains uuid [ OK ]"

        unset JOB_NAME

        echo
    done

    echo -e "\nRan\e[36m 21 \e[0masserts."
}


test_output_return() {
    # shellcheck disable=SC1091
    source .mkdkr
    unset JOB_NAME
    NAME="test_output_return"
    OUT_NAME=$(.... "$NAME")

    assertNotNull "$OUT_NAME"
    [[ "$?" == "0" ]] && \
        _prn_exec "assert ${OUT_NAME} return output [ OK ]"

    # shellcheck disable=SC1001
    assertEquals "$([[ "$OUT_NAME" =~ ^.*_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12} ]] && echo true )" "true"
    [[ "$?" == "0" ]] && \
        _prn_exec "assert ${OUT_NAME} contains uuid [ OK ]"

    echo -e "\nRan\e[36m 2 \e[0masserts."
}


test_keep_session_name() {
    # shellcheck disable=SC1091
    source .mkdkr

    unset JOB_NAME
    .... "first_job_name"

    _FIRST_JOB_NAME="$JOB_NAME"

    .... "new_job_name"

    assertEquals "$JOB_NAME" "$_FIRST_JOB_NAME"
    [[ "$?" == "0" ]] && \
        _prn_exec "assert ${JOB_NAME} last JOB_NAME not changed [ OK ]"

    echo -e "\nRan\e[36m 1 \e[0masserts."
}

# shellcheck disable=SC1091
. ./shunit2
